"""empty message

Revision ID: 06e3d153b45e
Revises: 09687423913d
Create Date: 2024-02-15 11:53:12.075813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e3d153b45e'
down_revision = '09687423913d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_barcode', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_code', schema=None) as batch_op:
        batch_op.drop_column('log_barcode')

    # ### end Alembic commands ###
