"""empty message

Revision ID: 09687423913d
Revises: c879bf4a5a0f
Create Date: 2024-01-30 13:45:19.812873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09687423913d'
down_revision = 'c879bf4a5a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
