"""Lessones


Revision ID: 1e0dae60e4a2
Revises: f31acaa89cd5
Create Date: 2023-12-30 13:07:43.849336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0dae60e4a2'
down_revision = 'f31acaa89cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_iframe', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('play_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('filelink', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.drop_column('video_url')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Wallet', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('Wallet')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('file_name')
        batch_op.drop_column('filelink')
        batch_op.drop_column('play_count')
        batch_op.drop_column('video_iframe')

    op.drop_table('my_course')
    # ### end Alembic commands ###
