"""Your migration message

Revision ID: 566caa92917e
Revises: 536b53849ebe
Create Date: 2024-02-17 13:22:12.556431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566caa92917e'
down_revision = '536b53849ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lessonTime', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('lessonTime')

    # ### end Alembic commands ###
