"""empty message

Revision ID: 5cbbb43989ef
Revises: 6e97fea17b22
Create Date: 2024-01-07 16:09:38.797634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbbb43989ef'
down_revision = '6e97fea17b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iframe', sa.Text(), nullable=False))
        batch_op.drop_column('file_name')
        batch_op.drop_column('filelink')
        batch_op.drop_column('video_iframe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_iframe', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('filelink', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('iframe')

    # ### end Alembic commands ###
