"""empty message

Revision ID: 6e97fea17b22
Revises: d4f90dd6ae57
Create Date: 2024-01-03 11:58:14.770426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e97fea17b22'
down_revision = 'd4f90dd6ae57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    with op.batch_alter_table('wallet_log', schema=None) as batch_op:
        batch_op.drop_column('Wallet_id')
        batch_op.drop_column('Wallet_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Wallet_token', sa.VARCHAR(length=25), nullable=True))
        batch_op.add_column(sa.Column('Wallet_id', sa.INTEGER(), nullable=True))

    op.create_table('wallet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=100), nullable=True),
    sa.Column('token', sa.VARCHAR(length=25), nullable=True),
    sa.Column('Amount', sa.INTEGER(), nullable=True),
    sa.Column('TC', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
