"""Your migration message11

Revision ID: 7f45ca56955a
Revises: 566caa92917e
Create Date: 2024-02-17 13:47:36.434124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f45ca56955a'
down_revision = '566caa92917e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lessonTime', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('lessonTime')

    # ### end Alembic commands ###
