"""test migrate1

Revision ID: f31acaa89cd5
Revises: 1944cd8e25ad
Create Date: 2023-12-29 21:56:19.036912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31acaa89cd5'
down_revision = '1944cd8e25ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
